/******************************************************************************
 * File hal_mcp79410.c
 *
 *  Created on: 17 de jul. de 2026
 *      Author: Tassio Lima dos Santos
 *      Email: desenvolvimento20@globalsonic.com.br
 *****************************************************************************/



/******************************************************************************
 * Includes
 *****************************************************************************/

#include "mcp79410_memory_map.h"
#include "mcp79410_config.h"
#include "hal_mcp79410.h"
#include "../GS_stack/gs_hal_i2c.h"
#include "em_i2c.h"

/******************************************************************************
 * Defines
 *****************************************************************************/

//#define DEBUG

#define MCP79410_SRAM_AND_RTCC_REGISTER_I2C_BUS_ADDRESS     (0b01101111 << 1)           /**< I2C bus address*/
#define MCP79410_EEPROM_I2C_BUS_ADDRESS                     (0b01010111 << 1)           /**< I2C bus address*/

/******************************************************************************
 * Data types
 *****************************************************************************/

typedef struct {
  // Timekeeping Registers
  struct {
    uint8_t rtcsec_data;
    uint8_t rtcmin_data;
    uint8_t rtchour_data;
    uint8_t rtcwkday_data;
    uint8_t rtcdate_data;
    uint8_t rtcmth_data;
    uint8_t rtcyear_data;
    uint8_t control_data;
    uint8_t osctrim_data;
    uint8_t eeunlock_data;
  } __attribute__((packed)) timekeeping_registers;

  // Alarms Registers
  struct {
    uint8_t almsec_data;
    uint8_t almmin_data;
    uint8_t almhour_data;
    uint8_t almwkday_data;
    uint8_t almdate_data;
    uint8_t almmth_data;
  } __attribute__((packed)) alarm_registers[2];

  // Power-Fail Time-Stamp Registers
  struct {
    uint8_t pwrdnmin_data;
    uint8_t pwrdnhour_data;
    uint8_t pwrdndate_data;
    uint8_t pwrdnmth_data;
    uint8_t pwrupmin_data;
    uint8_t pwruphour_data;
    uint8_t pwrupdate_data;
    uint8_t pwrupmth_data;
  } __attribute__((packed)) power_fail_registers;

} __attribute__((packed)) st_mcp79410_registers_t;

/******************************************************************************
 * Static Variables
 *****************************************************************************/

static st_mcp79410_registers_t mcp79410_registers;

/******************************************************************************
 * Extern
 *****************************************************************************/

/******************************************************************************
 * Private Function Prototypes
 *****************************************************************************/

static I2C_TransferReturn_TypeDef write_to_register   (uint8_t register_address, const uint8_t* data_array, uint16_t data_size);
static I2C_TransferReturn_TypeDef read_from_register  (uint8_t register_address, uint8_t* read_data, uint16_t* read_data_size);
static void set_external_crystal                      (bool enable_external_crystal);

/*******************************************************************************
 * Function name: MCP79410_init
 *
 * Description  : Initialize the MCP79410 RTCC
 * Parameters   : INPUT bool is_there_external_crystal - tells if there is an external crystal circuit to generate the MCP79410's clock,
 *                                                       if there is not an external crystal, the MCP79410 will expect an external clock
 *                                                       generated by another component
 *                INPUT bool is_24hr_mode              - tells whether the MCP79410 will use 24 or 12 hours
 *                INPUT bool is_battery_enabled        - tells whether the battery is enabled
 *                INPUT st_timedate_t initial_timedate - data of the initial time-date when you initialize the component
 * Returns      : void
 *
 * Known issues :
 * Note         :
 ******************************************************************************/
void MCP79410_init(bool is_there_external_crystal, bool is_24hr_mode, bool is_battery_enabled, st_timedate_t initial_timedate)
{
#if (defined(MCP79410_ENABLE_PORT) && defined(MCP79410_ENABLE_PIN))
  GPIO_PinModeSet(MCP79410_ENABLE_PORT, MCP79410_ENABLE_PIN, gpioModePushPull, 1);
#endif // (defined(MCP79410_ENABLE_PORT) && defined(MCP79410_ENABLE_PIN))

  gs_hal_i2c_class()->i2cInit(MCP79410_PERIPHERAL, MCP79410_SCL_PORT, MCP79410_SCL_PIN, MCP79410_SDA_PORT, MCP79410_SDA_PIN);

  set_external_crystal(is_there_external_crystal);

}

static I2C_TransferReturn_TypeDef write_to_register(uint8_t register_address, const uint8_t* data_array, uint16_t data_size)
{
  if(data_array == NULL) return (i2cTransferUsageFault);
  if(register_address >= MCP79410_RTCC_REGISTERS_END_ADDRESS){
    return (i2cTransferUsageFault);
  }

  uint8_t write_data[data_size + 1];
  write_data[0] = register_address;
  memcpy(write_data + 1, data_array, data_size);
  data_size++;

  I2C_TransferReturn_TypeDef ret = gs_hal_i2c_class()->i2cSimpleTransfer(I2C_FLAG_WRITE,
                                                                         MCP79410_SRAM_AND_RTCC_REGISTER_I2C_BUS_ADDRESS,
                                                                         write_data, &data_size,
                                                                         NULL, NULL);

  return (ret);
}

static I2C_TransferReturn_TypeDef read_from_register(uint8_t register_address, uint8_t* read_data, uint16_t* read_data_size)
{
  if(read_data == NULL || read_data_size == NULL) return (i2cTransferUsageFault);
  if(register_address >= MCP79410_RTCC_REGISTERS_END_ADDRESS){
    return (i2cTransferUsageFault);
  }

  uint16_t write_size = 1;
  uint8_t write_data[1] = {register_address};

  I2C_TransferReturn_TypeDef ret = gs_hal_i2c_class()->i2cSimpleTransfer(I2C_FLAG_WRITE_READ,
                                                                         MCP79410_SRAM_AND_RTCC_REGISTER_I2C_BUS_ADDRESS,
                                                                         write_data, &write_size,
                                                                         read_data, read_data_size);

  return (ret);
}

static void set_external_crystal(bool enable_external_crystal)
{
  if(enable_external_crystal){
    mcp79410_registers.timekeeping_registers.rtcsec_data |= (1U << ST_OFFSET);
    mcp79410_registers.timekeeping_registers.control_data &= ~(1U << EXTOSC_OFFSET);
  }
  else
  {
    mcp79410_registers.timekeeping_registers.rtcsec_data &= ~(1U << ST_OFFSET);
  }
}

void set_timedate(st_timedate_t timedate_data)
{

}




























